// Generated by CoffeeScript 1.6.3
(function() {
  var escape, replaceList, str2js;

  replaceList = [[/\\/g, '\\\\'], [/\"/g, '\\"'], [/\n/g, '\\n'], [/\r/g, '\\r']];

  escape = function(s) {
    var x, y, _i, _len, _ref;
    for (_i = 0, _len = replaceList.length; _i < _len; _i++) {
      _ref = replaceList[_i], x = _ref[0], y = _ref[1];
      s = s.replace(x, y);
    }
    return s;
  };

  str2js = function(obj, key, str) {
    return "(" + obj + " || (" + obj + " = {}))[\"" + (escape(key)) + "\"] = \"" + (escape(str)) + "\";";
  };

  module.exports = str2js;

}).call(this);
